---
kind: pipeline
name: default

steps:
  - name: build
    image: golang:1.12
    environment:
      CGO_ENABLED: "0"
      GOOS: linux
      GOARCH: amd64
      GO11MODULE: on
    commands:
      - go vet ./...
      - go build -ldflags "-w -s" -o drone-oss-cache .
  - name: build-and-push-image
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      repo: daixijun1990/drone-oss-cache
      auto_tag: true
